export const storyMessages = {
  Advancement: {
    "Chi Gathering": {
      1: "You are not a cultivator.\n\nFor fifteen years, you have lived as a farmer and hunter in the Valley of Wei. On a hunting trip, late at night, you heard terrible sounds like the end of the world, and saw a light that lit up the sky like day. Two cultivators, flying through the air like gods, in a mighty duel that set the very heavens on fire. You thought yourself privileged to have witnessed such a sight in your humble life...until you returned home. Your entire village is gone, destroyed, obliterated...likely by a casual deflection of one of these almighty beings.\n\nAfter a few days to mourn, to grieve, you begin to think of your future. While living off the land is no issue for you, there is nothing left for you here. You will need to leave the Valley, the only home you have ever known, and pursue your fortunes elsewhere. And yet...all your life, you've been told about the monstrous spirit beasts outside this valley. Only the greatest fighters of your village, who had proceeded beyond the Chi Gathering stage and become more than mortal, can stand against them. It would take years, maybe decades for you to reach that level as an untrained farmer.\n\nBut you have nothing but time. Closing your eyes, you sit in a lotus position, and begin to cultivate.",
      2: "With nothing to do but hunt, manage your campsite, and cultivate, you find yourself making quite solid progress. You may not be a fabled genius like the stories, but a few hours a day of diligent practice has gotten you somewhere. Today, you found the ruins of the library, and collected some of your village's meager cultivation manuals. While most of them are beyond you, you're able to begin practicing the art of meditation almost immediately, deepening and strengthening your cultivation. Perhaps you can also improve your general reading level as well, and learn to get more out of the scrolls as you advance?",
      3: "Today you figured out the chi-as-whirlpool metaphor your books kept telling you. Your body and dantian want to be filled, they want to take in the chi of the universe. By circling your chi in a smooth motion, the very motion itself draws more chi in a reinforcing cycle. This is essential, since each meridian is exponentially harder to cleanse than the one before. It is said that master cultivators need to pull chi from hundreds of miles to climb the impossible walls the gods have set before immortality. For now, you'll settle for a few feet.",
      4: "Rereading your manuals over and over, empowering your skills and your body with chi, the things you learn are beginning to compound on each other. Understanding a sword form's circular steps helps you move your chi in a steady flow around your body. The calm of a placid lake allows you to reinforce the calm in your own soul. You still haven't touched on anything you'd call enlightenment, but with enough insights, you might make a real cultivator yet.",
      5: "Your chi is growing denser, brighter, and cleaner. The same motions that were made when you first started can now be made over and over again, refining your body just a little more each time. Every day, you gain a little more out of these exercises, and you find that even the simplest breathing exercises have a depth that seems unending. Truly, one could spend a lifetime just studying the most basic patterns, and still have barely begun to learn.",
      6: "You're starting to notice the benefit, now. Your skin is clearer, you can run faster, and logs that used to take all your strength to drag to the fire are now merely difficult. Though you are still very much mortal, as you were starkly reminded of when you stumbled upon a moon bear in the forest. You backed away slowly, and carefully, knowing you stood no chance against such a beast. At some point, you should probably train your martial skills as well - but without the Foundation stage, you can never learn the aura techniques a true cultivator uses. Until then, you're just preparing for that day.",
      7: "Your cultivation was once sufficiently brittle that only the purest, most unaspected chi could be filtered into your dantian. Now, with your increased experience, you finally feel comfortable branching out, taking on chi mixed with small whiffs of elemental aura, or tiny impurities. While cleansing it is rather labor intensive, you have the time to spare. Collecting pure chi is now almost as effortless as breathing, and you can use the extra time to expand your reach both deeper and wider.",
      8: "You've started to toughen your body, in preparation for your martial training. You've been punching trees, walking over sharp stones, and lifting small boulders. While you still damage yourself almost as much as the tree bark, you can tell you're stronger and tougher than ever. Soon, after a couple more meridians, you'll finally be ready to take on an elemental aspect, and learn the arts of combat. You've always been told fearsome monsters lie outside this valley. Someday soon, you'll see how fearsome they really are.",
      9: "You're almost there. You can meditate for hours in silence. You can read the Five Classics, and almost understand them. Your chi reinforces itself, growing brighter by the day as the impurities of your mortal form are cleansed by your chi, like water wearing at a rock. Today, you met the bear again, and it recognised something in you, giving you the space of a fellow predator to be respected. Soon you'll be ready to take the step into Foundation, to project chi and intent, and protect yourself against the spirit beasts that roam the wilds. Though still far, far away from the immortal beings of the heavens, you will become more than a mere mortal. You will be a cultivator."
    },
    "Foundation": {
      1: "The world has opened up to you. With your keener insight now, you realise this valley's chi is weak and faded. You always wondered why spirit beasts don't come here. Now, you realise that as beings of chi, the world is gray and gloomy for them. To continue your cultivation, you'll need to find richer sources of aura - but that will attracts others as well, so you'll need to be prepared to defend yourself. Now that you can wreathe parts of your body in an aura of chi, you can finally empower yourself beyond mere muscular strength. You can also choose an elemental aspect - interestingly, your manual's tests show that you have no real affinity for any of them. At least that means you can take your pick - any element you choose will give you vastly increased benefit from that element, and you'll need it in order to train and use your abilities in combat!"
    }
  }
};